### ISSUE TITLE
Do not work with relations?

### ISSUE THREAD

**Issue by 4n70w4** [SpiritSaint/nova-gridder#2]
I tried `HasMany` and nothing happening.
It would be very useful to display 2 or 3 tables of relations in one row.

**Comment by Zen0x7** [comment]
Hi @4n70w4.

As I understand it, relationships like hasMany prints independently to the fields. 

Right now I will get to work with this project, to support nova 3.0 and other things. I'll see what I can do about it. I can not guarantee that I can do something but if I get something I will let you know.
